kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: edgefs-nfs-csi-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: io.edgefs.csi.nfs
parameters:
  segment: rook-edgefs
  service: nfs01
  #tenant: kslab-infra-operator
